apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: healthcare-ingress
spec:
  rules:
  - http:
      paths:
      - path: /patient
        pathType: Prefix
        backend:
          service:
            name: patient-service
            port:
              number: 80
